name: Generate Folder Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate folder structure JSON
      run: |
        # Install jq jika belum ada
        sudo apt-get update
        sudo apt-get install -y jq

        # Iterasi file dan folder
        folder_structure=$(find . -type d ! -path "./.git*" -print0 | while IFS= read -r -d '' folder; do
          last_modified=$(git log -1 --format=%ci -- "$folder")
          echo "{\"name\": \"$(basename "$folder")\", \"path\": \"${folder#./}\", \"sha\": \"$(git log -1 --format=%H -- "$folder")\", \"size\": 0, \"url\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${folder#./}?ref=main\", \"html_url\": \"https://github.com/${GITHUB_REPOSITORY}/tree/main/${folder#./}\", \"git_url\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/git/trees/$(git rev-parse HEAD):${folder#./}\", \"download_url\": null, \"type\": \"dir\", \"last_modified\": \"$last_modified\", \"_links\": {\"self\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${folder#./}?ref=main\", \"git\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/git/trees/$(git rev-parse HEAD):${folder#./}\", \"html\": \"https://github.com/${GITHUB_REPOSITORY}/tree/main/${folder#./}\"}},"
        done)

        files_structure=$(find . -type f ! -path "./.git*" -print0 | while IFS= read -r -d '' file; do
          size=$(stat -c %s "$file")
          sha=$(git log -1 --format=%H -- "$file")
          last_modified=$(git log -1 --format=%ci -- "$file")
          echo "{\"name\": \"$(basename "$file")\", \"path\": \"${file#./}\", \"sha\": \"$sha\", \"size\": $size, \"url\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${file#./}?ref=main\", \"html_url\": \"https://github.com/${GITHUB_REPOSITORY}/blob/main/${file#./}\", \"git_url\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/git/blobs/$sha\", \"download_url\": \"https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/${file#./}\", \"type\": \"file\", \"last_modified\": \"$last_modified\", \"_links\": {\"self\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${file#./}?ref=main\", \"git\": \"https://api.github.com/repos/${GITHUB_REPOSITORY}/git/blobs/$sha\", \"html\": \"https://github.com/${GITHUB_REPOSITORY}/blob/main/${file#./}\"}},"
        done)

        # Gabungkan JSON
        combined_json="[${folder_structure}${files_structure%,}]"

        # Simpan ke file
        echo "$combined_json" > file-structure.json

    - name: Commit and push file structure
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add file-structure.json
        git commit -m "Update file structure JSON"
        git push
