name: Generate Folder Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate folder structure JSON
      run: |
        # Install jq jika belum ada
        sudo apt-get update
        sudo apt-get install -y jq

        # Fungsi untuk mendapatkan informasi file
        get_file_info() {
          file_path="$1"
          created_at=$(stat -c %w "$file_path" 2>/dev/null || stat -c %y "$file_path")
          updated_at=$(stat -c %y "$file_path")
          size=$(stat -c %s "$file_path")
          echo "\"created_at\": \"$created_at\", \"updated_at\": \"$updated_at\", \"size\": $size"
        }

        # Iterasi file dan folder
        folder_structure=$(find . -type d ! -path "./.git*" -print0 | while IFS= read -r -d '' folder; do
          echo "{\"name\": \"$(basename "$folder")\", \"path\": \"${folder#./}\", \"type\": \"dir\", $(get_file_info "$folder")},"
        done)

        files_structure=$(find . -type f ! -path "./.git*" -print0 | while IFS= read -r -d '' file; do
          echo "{\"name\": \"$(basename "$file")\", \"path\": \"${file#./}\", \"type\": \"file\", $(get_file_info "$file")},"
        done)

        # Gabungkan JSON
        combined_json="[${folder_structure}${files_structure%,}]"

        # Simpan ke file
        echo "$combined_json" > file-structure.json

    - name: Commit and push file structure
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add file-structure.json
        git commit -m "Update file structure JSON"
        git push
